/**
 * The README's badge and `/api.json` are one contract, written in two places.
 *
 * The first line of the README is a shields.io badge whose URL carries a JSONPath:
 * `query=%24.exports.total`, pointed at `https://edfcore.vercel.app/api.json`. That endpoint is
 * generated by `website/src/pages/api.json.ts` from the three built entry points, and it exists so
 * the badge counts the API rather than repeating a number someone typed — the site footer read
 * "Version 0.1.0" for three minor series and that is the failure this design avoids.
 *
 * The two halves have never been compared. Renaming `total` to `count` in the endpoint, or
 * nesting it one level deeper, leaves the badge querying a path that no longer exists — and
 * shields.io does not fail loudly for that. It renders "invalid" or an empty value in the corner
 * of the README, which is the one place nobody looks after the first week.
 *
 * So the path is extracted from the badge URL and walked through the object the endpoint builds.
 * The endpoint itself cannot be imported — it lives under `website/`, and importing it would drag
 * in a tsconfig the CI check does not install (0.4.264) — so the shape is rebuilt here from the
 * same three modules it uses, and the source is read as text to confirm it still computes the
 * same field the same way.
 */

import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import * as universal from '../../src/index.js';
import * as nodeEntry from '../../src/node.js';
import * as validateEntry from '../../src/validate.js';

const ROOT = new URL('../../', import.meta.url);
const read = (relative: string): string => readFileSync(new URL(relative, ROOT), 'utf8');

const README = read('README.md');
const ENDPOINT = read('website/src/pages/api.json.ts');

/** `query=%24.exports.total` -> `['exports', 'total']`. */
const BADGE_PATH: readonly string[] = (() => {
  const match = /query=([^&)\s]+)/.exec(README);
  if (match === null) return [];
  return decodeURIComponent(match[1] as string)
    .replace(/^\$\.?/, '')
    .split('.')
    .filter((part) => part !== '');
})();

/** The URL the badge points at, so a moved endpoint is caught too. */
const BADGE_URL = decodeURIComponent(/url=([^&)\s]+)/.exec(README)?.[1] ?? '');

/** What `api.json.ts` builds, rebuilt from the same three modules. */
const BODY = (() => {
  const entries = {
    edfcore: Object.keys(universal).length,
    'edfcore/node': Object.keys(nodeEntry).length,
    'edfcore/validate': Object.keys(validateEntry).length,
  };
  return {
    version: universal.VERSION,
    entryPoints: Object.keys(entries).length,
    exports: { ...entries, total: Object.values(entries).reduce((sum, one) => sum + one, 0) },
  };
})();

describe('the badge was read', () => {
  it('carries a query and a url, so a passing run is not a vacuous one', () => {
    expect(BADGE_PATH.length).toBeGreaterThan(0);
    expect(BADGE_URL).toContain('/api.json');
  });

  it('points at the endpoint this repository serves', () => {
    // `api.json.ts` under `pages/` is served at `/api.json`; the homepage is where it is hosted.
    const homepage = (JSON.parse(read('package.json')) as { homepage: string }).homepage;
    expect(BADGE_URL.startsWith(homepage)).toBe(true);
  });
});

describe('the queried path resolves in what the endpoint returns', () => {
  it('walks to a value', () => {
    let value: unknown = BODY;
    for (const key of BADGE_PATH) {
      expect(value, `nothing at ${BADGE_PATH.join('.')}`).toBeTypeOf('object');
      value = (value as Record<string, unknown>)[key];
    }
    expect(value, `the badge asks for ${BADGE_PATH.join('.')}`).toBeTypeOf('number');
    expect(value).toBeGreaterThan(40);
  });

  it('and the endpoint still computes it the same way', () => {
    // Read as text rather than imported: this file lives under `website/`, and importing it would
    // pull in a tsconfig the CI check does not install.
    for (const fragment of ['exports', 'total', 'Object.keys(universal).length']) {
      expect(ENDPOINT, `api.json.ts no longer mentions ${fragment}`).toContain(fragment);
    }
  });

  it('counts what the README table counts', () => {
    // The badge and the "Functions, classes and constants" row are the same number by different
    // routes; `api-surface.test.ts` owns that row, so a disagreement here is the badge's.
    const claimed = /\| Functions, classes and constants \| (\d+) \|/.exec(README);
    expect(claimed, 'no API surface row in README.md').not.toBeNull();
    expect(BODY.exports.total).toBe(Number(claimed?.[1]));
  });
});
