/**
 * `vercel.json` describes the site this repository builds.
 *
 * It is the one configuration file here that nothing reads on a normal day: the tests do not need
 * it, `npm run check` does not touch it, and it takes effect on a machine none of us watches. Its
 * four couplings are all silent when broken.
 *
 *  - The build command names four scripts across two workspaces. A renamed script fails the
 *    deploy, which is the loud one — but only after a green push.
 *  - `outputDirectory` is where the deploy looks for the built site, and `check-site-output.mjs`
 *    is where CI looks for the same thing. If those parted, one of them would be inspecting a
 *    directory nobody serves.
 *  - Two `Content-Type: text/plain` rules name `/llms.txt` and `/llms-full.txt`. If either
 *    generator moved, the rule would match nothing and the endpoint would arrive as a download
 *    rather than a page — while `check-site-output.mjs` still found the file in `dist/` and
 *    passed.
 *  - `trailingSlash` is stated here and again in `astro.config.mjs`, in different vocabularies.
 *    The two must mean the same thing; disagreeing gives every documentation URL a redirect it
 *    did not ask for.
 *
 * The `Permissions-Policy` row is checked for a different reason. `inspector-privacy.test.ts`
 * proves the demo sends nothing; this is the other half — the response headers that keep the page
 * from being able to ask for a camera, a microphone or a location in the first place. That is the
 * kind of line that gets dropped in a config tidy-up because nothing appears to use it.
 *
 * What this does NOT check: that Vercel honours any of it. This is a check that the repository
 * agrees with itself about what it is deploying.
 */

import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const ROOT = new URL('../../', import.meta.url);
const read = (relative: string): string => readFileSync(new URL(relative, ROOT), 'utf8');

interface HeaderRule {
  readonly source: string;
  readonly headers: ReadonlyArray<{ readonly key: string; readonly value: string }>;
}

const VERCEL = JSON.parse(read('vercel.json')) as {
  buildCommand: string;
  outputDirectory: string;
  cleanUrls: boolean;
  trailingSlash: boolean;
  headers: readonly HeaderRule[];
};

const ROOT_SCRIPTS = new Set(
  Object.keys((JSON.parse(read('package.json')) as { scripts: object }).scripts),
);
const SITE_SCRIPTS = new Set(
  Object.keys((JSON.parse(read('website/package.json')) as { scripts: object }).scripts),
);
const ASTRO_CONFIG = read('website/astro.config.mjs');
const SITE_CHECK = read('scripts/check-site-output.mjs');

/** `npm run build`, `npm --prefix website run check` — the script and the workspace it belongs to. */
const BUILD_STEPS: ReadonlyArray<{ readonly script: string; readonly workspace: 'root' | 'site' }> =
  [...VERCEL.buildCommand.matchAll(/npm\s+(--prefix\s+(\S+)\s+)?run\s+([\w:]+)/g)].map((match) => ({
    script: match[3] as string,
    workspace: match[2] === undefined ? 'root' : 'site',
  }));

describe('the build command', () => {
  it('was parsed, so a passing run is not a vacuous one', () => {
    expect(BUILD_STEPS.length).toBeGreaterThanOrEqual(3);
    expect(BUILD_STEPS.some((step) => step.workspace === 'site')).toBe(true);
    expect(BUILD_STEPS.some((step) => step.workspace === 'root')).toBe(true);
  });

  it.each(BUILD_STEPS.map((step) => [step.workspace, step.script] as const))(
    'names a %s script that exists: %s',
    (workspace, script) => {
      expect((workspace === 'root' ? ROOT_SCRIPTS : SITE_SCRIPTS).has(script)).toBe(true);
    },
  );

  it('builds the library before the site, which imports it', () => {
    // The site's `api.json.ts` endpoint imports the three published entry points, so `dist/` has to
    // exist by then. `ci.yml` states the same ordering in a comment.
    const library = VERCEL.buildCommand.indexOf('npm run build');
    const site = VERCEL.buildCommand.indexOf('--prefix website run build');
    expect(library).toBeGreaterThan(-1);
    expect(site).toBeGreaterThan(library);
  });
});

describe('where the built site is', () => {
  it('is the directory the deploy serves and the directory CI inspects', () => {
    expect(VERCEL.outputDirectory).toBe('website/dist');
    // `check-site-output.mjs` builds the same path from its own root.
    expect(SITE_CHECK).toContain("join(ROOT, 'website', 'dist')");
  });
});

describe('the routes that must arrive as text', () => {
  it.each(['/llms.txt', '/llms-full.txt'])('%s is generated by a page that exists', (route) => {
    const rule = VERCEL.headers.find((entry) => entry.source === route);
    expect(rule?.headers[0]?.value).toBe('text/plain; charset=utf-8');
    // `src/pages/llms.txt.ts` is what serves `/llms.txt`; a rule for a route nothing generates is
    // a rule that never fires.
    expect(read(`website/src/pages${route}.ts`).length).toBeGreaterThan(100);
  });
});

describe('the two statements of the URL shape', () => {
  it('agree that a documentation URL has no trailing slash', () => {
    expect(VERCEL.trailingSlash).toBe(false);
    expect(ASTRO_CONFIG).toContain("trailingSlash: 'never'");
    // `cleanUrls` is what makes `/docs/quick-start` serve `quick-start.html`; without it the
    // extension-less links every page writes would 404.
    expect(VERCEL.cleanUrls).toBe(true);
  });
});

describe('the headers the inspector depends on', () => {
  const global = VERCEL.headers.find((entry) => entry.source === '/(.*)');
  const value = (key: string): string | undefined =>
    global?.headers.find((header) => header.key === key)?.value;

  it('refuse the page the devices it has no reason to want', () => {
    // The demo's whole claim is that a recording never leaves the machine. Nothing here can ask
    // for a camera, a microphone or a location even if a script tried.
    const policy = value('Permissions-Policy') ?? '';
    for (const feature of ['camera=()', 'microphone=()', 'geolocation=()']) {
      expect(policy).toContain(feature);
    }
  });

  it('keep the two that make a static site safe to serve', () => {
    expect(value('X-Content-Type-Options')).toBe('nosniff');
    expect(value('Referrer-Policy')).toBe('strict-origin-when-cross-origin');
  });
});
