/**
 * The share card is the image the page says it is.
 *
 * `og.png` is 537 KB of pixels that nothing in this repository opens. Every link to edfcore —
 * posted in a Slack channel, quoted in a paper, pasted into a chat — renders it, and it is the
 * only thing many people will ever see of this project. It is also the only binary here that is
 * regenerated by hand, from `design/og.svg`, through two commands in a README.
 *
 * Every coupling around it is silent when broken:
 *
 *  - `Base.astro` declares `og:image:width` and `og:image:height` to scrapers that lay out the
 *    preview before the bytes arrive. Wrong numbers letterbox or crop the card at the far end,
 *    where nobody who could fix it is looking.
 *  - The export is `qlmanage` then `sips -c 630 1200`, which crops the MIDDLE of a square
 *    thumbnail. That works because the canvas is 1200x1200 with the card in a centred band, so
 *    the band offset is half the leftover. Change the canvas and the crop takes the wrong rows —
 *    quietly, because a wrongly cropped card is still a card.
 *  - `og:image:alt` is the copy read aloud by a screen reader and shown when the image fails. It
 *    quotes the line the card prints, so rewording the card leaves the alt text describing an
 *    image that no longer exists.
 *
 * What this does NOT check: that `og.png` was exported from THIS `og.svg`. Comparing them would
 * mean rendering SVG, and nothing here can. It checks the dimensions, which is the property the
 * two commands are supposed to produce and the one every consumer of the card depends on.
 *
 * Nor does it check that the rendered wordmark FITS the safe zone — text extent needs the font.
 * The anchors are checked, which catches a card redrawn against a different canvas.
 */

import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const ROOT = new URL('../../', import.meta.url);
const read = (relative: string): string => readFileSync(new URL(relative, ROOT), 'utf8');

const BASE = read('website/src/layouts/Base.astro');
const SVG = read('website/design/og.svg');
const NOTE = read('website/design/README.md');
const PNG = readFileSync(new URL('website/public/og.png', ROOT));

/** `content` of a `<meta property="og:…">` or `<meta name="…">` in the layout. */
const meta = (attribute: string, name: string): string | undefined =>
  new RegExp(`<meta ${attribute}="${name}" content="([^"]*)"`).exec(BASE)?.[1];

/** The first attribute of the root `<svg>`, or of the band `<g transform>`. */
const svgAttribute = (name: string): string | undefined =>
  new RegExp(`${name}="([^"]*)"`).exec(SVG)?.[1];

/** Every `<text>` the card draws, in document order. */
const CARD_TEXT: readonly string[] = [...SVG.matchAll(/<text\b[^>]*>([^<]*)<\/text>/g)].map(
  (match) => (match[1] as string).trim(),
);

describe('the image the scrapers fetch', () => {
  it('is a PNG whose own header carries its size', () => {
    // The eight-byte signature, then a length, then `IHDR`: width and height are the two big-endian
    // words after it. Read from the bytes rather than from a tool, so this holds on any machine.
    expect(PNG.subarray(0, 8).toString('hex')).toBe('89504e470d0a1a0a');
    expect(PNG.subarray(12, 16).toString('latin1')).toBe('IHDR');
  });

  it('is the size the meta tags promise a scraper', () => {
    expect(String(PNG.readUInt32BE(16))).toBe(meta('property', 'og:image:width'));
    expect(String(PNG.readUInt32BE(20))).toBe(meta('property', 'og:image:height'));
  });

  it('is the size the design note documents', () => {
    expect(NOTE).toContain(`${PNG.readUInt32BE(16)}x${PNG.readUInt32BE(20)}`);
  });

  it('is served from the path the layout points at', () => {
    // `ogImage` is built from this literal, and `public/` is the site root.
    expect(BASE).toContain("new URL('/og.png', Astro.site)");
  });
});

describe('the source it was exported from', () => {
  const canvas = Number(svgAttribute('width'));
  const band = /<g transform="translate\(0,(\d+)\)">/.exec(SVG);
  const offset = Number(band?.[1]);

  it('is square, because Quick Look renders a square thumbnail', () => {
    expect(SVG).toContain(`viewBox="0 0 ${canvas} ${canvas}"`);
    expect(svgAttribute('height')).toBe(String(canvas));
    // And the note says why, so the next person does not "fix" the canvas to 1200x630.
    expect(NOTE).toContain('Quick Look always renders a square thumbnail');
  });

  it('centres the card band, which is the half `sips -c` keeps', () => {
    expect(band, 'no translated band in og.svg').not.toBeNull();
    const height = PNG.readUInt32BE(20);
    // The crop takes the middle `height` rows, so the band has to start where they do.
    expect(offset * 2 + height).toBe(canvas);
    expect(NOTE).toContain(`sips -c ${height} ${PNG.readUInt32BE(16)}`);
  });

  it('draws the band at the aspect the card is cropped to', () => {
    const ground = /<rect width="(\d+)" height="(\d+)" fill="#[0-9a-f]{6}"\/>/g;
    const sizes = [...SVG.matchAll(ground)].map((match) => `${match[1]}x${match[2]}`);
    expect(sizes).toContain(`${PNG.readUInt32BE(16)}x${PNG.readUInt32BE(20)}`);
  });

  it('anchors the wordmark inside the safe zone the note names', () => {
    const zone = /middle (\d+)x(\d+)/.exec(NOTE);
    expect(zone, 'no safe zone in the design note').not.toBeNull();
    const insetX = (PNG.readUInt32BE(16) - Number(zone?.[1])) / 2;
    const insetY = (PNG.readUInt32BE(20) - Number(zone?.[2])) / 2;
    const anchors = [...SVG.matchAll(/<text x="(\d+)" y="(\d+)"/g)].map(
      (match) => [Number(match[1]), Number(match[2])] as const,
    );
    expect(anchors.length).toBeGreaterThan(2);
    const outside = anchors.filter(
      ([x, y]) => x < insetX || y < insetY || y > PNG.readUInt32BE(20) - insetY,
    );
    expect(outside, 'text anchored outside the region no platform crops').toEqual([]);
  });
});

describe('the alt text describes this card', () => {
  const alt = /const ogImageAlt =\s*([\s\S]*?);\n/.exec(BASE)?.[1] ?? '';
  /** The literal as a reader hears it: the concatenation, without the quotes and the `+`. */
  const spoken = [...alt.matchAll(/'([^']*)'/g)].map((match) => match[1]).join('');

  it('was read, so a passing run is not a vacuous one', () => {
    expect(spoken.length).toBeGreaterThan(80);
    // Bound to the constant rather than retyped, and on both cards a scraper might read.
    expect(BASE).toContain('<meta property="og:image:alt" content={ogImageAlt} />');
    expect(BASE).toContain('<meta name="twitter:image:alt" content={ogImageAlt} />');
  });

  it('quotes the line the card actually prints', () => {
    // The alt text lowercases the opening word mid-sentence; the card capitalises it.
    const line = CARD_TEXT.find((text) => text.startsWith('Read EDF'));
    expect(line, 'the card no longer prints a "Read EDF…" line').toBeDefined();
    expect(spoken.toLowerCase()).toContain((line as string).toLowerCase());
  });

  it('names the annotation the card actually draws', () => {
    const event = CARD_TEXT.find((text) => /^Sleep stage/.test(text));
    expect(event, 'the card no longer draws a sleep-stage annotation').toBeDefined();
    expect(spoken).toContain('sleep-stage annotation');
  });

  it('calls the trace green, and the trace is green', () => {
    expect(spoken).toContain('phosphor-green');
    // The stroke is a gradient, so the colour lives in its stops.
    const stops = [...SVG.matchAll(/stop-color="#([0-9a-f]{6})"/g)].map(
      (match) => match[1] as string,
    );
    const green = stops.filter((hex) => {
      const [red, grn, blue] = [0, 2, 4].map((at) => Number.parseInt(hex.slice(at, at + 2), 16));
      return (grn as number) > (red as number) && (grn as number) > (blue as number);
    });
    expect(green.length, `no green among ${stops.join(', ')}`).toBeGreaterThan(0);
  });
});
